FROM template-gin-axum:dep AS builder

COPY src src
COPY sql sql

RUN cargo build --release 
RUN mv ./target/release/template-gin-axum ./x


FROM registry.cn-hangzhou.aliyuncs.com/jrjr/debian:12-slim

COPY --from=builder /app/x /bin

EXPOSE 8060
ENV TZ=Asia/Shanghai
CMD ["x"]