FROM registry.cn-hangzhou.aliyuncs.com/jrjr/rust:1.80.0-slim AS builder

WORKDIR /app

ENV RUSTUP_DIST_SERVER="https://rsproxy.cn"
ENV RUSTUP_UPDATE_ROOT="https://rsproxy.cn/rustup"

COPY conf/mirror/debian.sources /etc/apt/sources.list.d/debian.sources
RUN apt-get -y update
RUN apt-get -y install libssl-dev pkg-config
RUN cargo init

COPY Cargo.toml Cargo.toml
COPY Cargo.lock Cargo.lock
COPY .cargo .cargo
RUN cargo fetch