FROM registry.cn-hangzhou.aliyuncs.com/jrjr/rust:1.80.0-slim AS builder

WORKDIR /app

ARG APP_TARGET=x86_64-unknown-linux-musl

ENV RUSTUP_DIST_SERVER="https://rsproxy.cn"
ENV RUSTUP_UPDATE_ROOT="https://rsproxy.cn/rustup"

COPY conf/mirror/debian.sources /etc/apt/sources.list.d/debian.sources
RUN echo Y | apt-get update
RUN echo Y | apt-get install musl-tools

RUN rustup target add $APP_TARGET
RUN cargo init

COPY Cargo.toml Cargo.toml
COPY Cargo.lock Cargo.lock
COPY .cargo .cargo
RUN cargo fetch