FROM template-gin-axum:dep AS builder

ARG APP_TARGET=x86_64-unknown-linux-musl

COPY src src
RUN cargo build --release --target=$APP_TARGET 
RUN mv ./target/$APP_TARGET/release/template-gin-axum ./x


FROM registry.cn-hangzhou.aliyuncs.com/jrjr/alpine:3.20

COPY --from=builder /app/x /bin

EXPOSE 8060
ENV TZ=Asia/Shanghai
CMD ["x"]